### ISSUE TITLE
[1.7.10] Crash in combination with other mod, caused by recipe

### ISSUE THREAD

**Issue by Xaikii** [Shinoow/AbyssalCraft-Integration#14]
The information what is causing it exactly is listed in the FML Log.
And yes I am sure this is caused by AbyssalCraft-Integration, also gregtech is reporting an issue with that recipe. 
I'd like to ask for an option to disable the items including the recipes of this add-on.
Or a fix.

Crashlog:
https://pastebin.com/1VgA9Gdw

FML Log:
https://pastebin.com/SeaDPYWg

Greetings
- Xaikii

**Comment by Shinoow** [comment]
It seems like the 1.7.10 code contained a one letter typo for the registry name of an Item, which lead to the archaic item reference in my API package having a null Item in place of the reference (because of the aforementioned typo). The log error is caused by this, but the crash is caused by VoltzEngine not handling null value(s) [here](https://github.com/VoltzEngine-Project/Engine/blob/development/src/main/scala/com/builtbroken/mc/lib/data/ItemStackMap.java#L33) when logging the erroring recipe containing nulls.

As 1.7.10 development of AbyssalCraft ceased roughly 18 months ago (with the last 1.7.10 release of AbyssalCraft Integration being 11 months ago), I have no intentions of releasing any update rectifying this, as it is a Minecraft version that I no longer support. On the other hand, the actual crashing (as caught from the stacktrace of the log) is caused by VoltzEngine invoking toString on a null ItemStack when logging the recipe containing a null ItemStack, so they should make the adjustment there to properly handle the logging of any null ItemStacks, rather than enabling the game to crash from it not being handled (which I believe is unintentional on their end).
