### ISSUE TITLE
[Suggestion] Add dynamic trees.

### ISSUE THREAD

**Issue by Ziggurat7** [Shinoow/AbyssalCraft-Integration#41]
I'm not sure if this is in the scope of this patch, but it would be nice to have dynamic trees versions of the trees in the mod.

**Comment by Shinoow** [comment]
Seems like someone is planning on adding support in their Dynamic Trees addon https://github.com/supermassimo/DynamicTrees-ExC/issues/1 https://github.com/supermassimo/DynamicTrees-ExC/issues/14, so I think I'll leave it to them, since they seem to have the knowhow on adding Dynamic Trees compatibility.
