### ISSUE TITLE
Startup Crash - 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shinoow/AbyssalCraft-Integration#7]
https://gist.github.com/P3rf3ctXZer0/9b094bb8653ec4df201faf61f3353938

**Comment by Shinoow** [comment]
AbyssalCraft Integration currently does not support Better Questing 2.x.x, so the Better Questing integration can't be used with that version of Better Questing. Once I release an update fixing some other stuff, I'm gonna make an official port to 1.10.2 (instead of relying on the 1.9.4 port to work in 1.10.2), and that will include the Better Questing stuff being ported to BQ 2.x.x.

**Comment by P3rf3ctXZer0** [comment]
Can I disable it via a config?

**Comment by Shinoow** [comment]
Yup, all integrations can be disabled in the config.
